default: &default
  adapter: "postgresql"
  encoding: "unicode"
  database: <%= ENV.fetch("POSTGRES_DB") { "hrms_development" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  gssencmode: disable

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "growth" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "growth" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "growth" } %>_production
